config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :statuses
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'statuses#index'
  # Making Friends ---------------------
  resources :users, only: [:index, :show]    
   resources :friendships, only: [:create, :destroy, :accept] do 
    member do 
      put :accept
    end
  end
    # Making Friends ---------------------
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
	belongs_to :friend, class_name: "User"
	
	def accept_friendship
		self.update_attributes(friend_status: "active", friended_at: Time.now)
	end

	def deny_friendship
		self.destroy
	end

	def cancel_friendship
		self.destroy
	end
end

app/models/status.rb
class Status < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :statuses



  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>", 
  micro: "40x40>" }, default_url:  "ina.jpeg"  
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/ 

  has_many :friendships, dependent: :destroy
  has_many :inverse_friendships, class_name: "Friendship", foreign_key: "friend_id", dependent: :destroy

  def request_friendship(user_2)
  	self.friendships.create(friend: user_2)
  end
  
  def pending_friend_requests_from
    self.inverse_friendships.where(friend_status: "pending")
  end
  
  def pending_friend_requests_to
    self.friendships.where(friend_status: "pending")
  end
  
  def active_friends
    self.friendships.where(friend_status: "active").map(&:friend) + self.inverse_friendships.where(friend_status: "active").map(&:user)
  end
  
    def friendship_status(user_2)
    friendship = Friendship.where(user_id: [self.id,user_2.id], friend_id: [self.id,user_2.id])
    unless friendship.any?
      return "not_friends"
    else
      if friendship.first.friend_status == "active"
        return "friends"
      else
        if friendship.first.user == self
          return "pending"
        else
          return "requested"
        end
      end
    end
  end
  
  def friendship_relation(user_2)
    Friendship.where(user_id: [self.id,user_2.id], friend_id: [self.id,user_2.id]).first
  end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, 
                                                          :password, 
                                                          :password_confirmation,
                                                          :username,
                                                          :image
                                                          ) 
                                                          }
  devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:email, 
                                                          :password, 
                                                          :password_confirmation, 
                                                          :current_password, 
														                              :username,
                                                          :image
                                                          ) 
                                                          }  
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
	before_action :authenticate_user!
	before_action :set_user, only: [:create]
	before_action :set_friendship, only: [:destroy, :accept]

	def create
		@friendship = current_user.request_friendship(@user)
		respond_to do |format|
			format.html {redirect_to users_path, notice: "Friendship Created"}
		end
	end

	def destroy
		@friendship.destroy
		respond_to do |format|
			format.html {redirect_to users_path, notice: "Friendship Deleted"}
		end
	end

	def accept
		@friendship.accept_friendship
		#@friendship.create_activity key: 'friendship.accepted', owner: @friendship.user, recipient: @friendship.friend
		#@friendship.create_activity key: 'friendship.accepted', owner: @friendship.friend, recipient: @friendship.user
		respond_to do |format|
			format.html {redirect_to users_path, notice: "Friendship Accepted"}
		end
	end

	private

	def set_user
		@user = User.find(params[:user_id])
	end

	def set_friendship
		@friendship = Friendship.find(params[:id])
	end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = current_user.statuses.build
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = current_user.statuses.build(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:name, :content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_the_user, only: [:show]
  

# Making Friends ---------------------  
	def index
	case params[:people] when "friends"
      @users = current_user.active_friends
    when "requests"
      @users = current_user.pending_friend_requests_from.map(&:user)
    when "pending"
      @users = current_user.pending_friend_requests_to.map(&:friend)
    else
      @users = User.where.not(id: current_user.id)
    end
	end
# Making Friends ---------------------	


  def show
  end
  
  
    private
    
    def set_the_user
      @user = User.find_by(username: params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def action_buttons(user)
		case current_user.friendship_status(user) when "friends"
			link_to "Cancel Friendship", friendship_path(current_user.friendship_relation(user)), method: :delete
		when "pending"
			link_to "Cancel Request", friendship_path(current_user.friendship_relation(user)), method: :delete
		when "requested"
			link_to "Accept", accept_friendship_path(current_user.friendship_relation(user)), method: :put
		when "not_friends"
			link_to "Add as Friend", friendships_path(user_id: user.id), method: :post
		end
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Socialville</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navigation/navbar' %>
  <%= bootstrap_flash %>
  	<div class="container">
  		<%= yield %>
  	</div>
    
  </body>
</html>

app/views/layouts/navigation/_nav_left.html.erb
<li><%= link_to "Statuses", statuses_path if current_user %></li> 
<li><a href="#">Link</a></li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
  <ul class="dropdown-menu">
    <li><a href="#">Action</a></li>
    <li><a href="#">Another action</a></li>
    <li><a href="#">Something else here</a></li>
    <li role="separator" class="divider"></li>
    <li><a href="#">Separated link</a></li>
    <li role="separator" class="divider"></li>
    <li><a href="#">One more separated link</a></li>
  </ul>
</li>

app/views/layouts/navigation/_nav_right.html.erb
<% if !current_user %>
  <li><%= link_to "Sign Up", new_user_registration_path %></li>
  <li><%= link_to "Sign In", new_user_session_path %></li>
<% end %>  
  
<% if current_user %>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" 
    data-toggle="dropdown" role="button" aria-haspopup="true" 
    aria-expanded="false"><%= current_user.username %> <span class="caret"></span></a>
    <ul class="dropdown-menu">
      <li><%= link_to "Edit My Profile", edit_user_registration_path %></li>
      <li role="separator" class="divider"></li>
      <li><%= link_to "End my session", 
            destroy_user_session_path, method: :delete %></li>
    </ul>
  </li>
<% end %>

app/views/layouts/navigation/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Socialville", root_path, class:"navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation/nav_left' %>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation/nav_right' %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/statuses/_form.html.erb
<%= form_for(status) do |f| %>
  <% if status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/statuses/_index.html.erb
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
<div class="row bootstrap snippets">
    <div class="col-md-6 col-xs-12 col-md-offset-3">
      <div class="panel" id="messge">
        <div class="panel-heading">
          <h3 class="panel-title">Message</h3>
        </div>
        <div class="panel-body">
          <ul class="list-group list-group-full">   
          </ul>
        </div>
      </div>
    </div>
</div>

app/views/statuses/_show.html.erb
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
<div class="container bootstrap snippet">
    <div class="row">
        
    </div>
</div>

app/views/statuses/edit.html.erb
<h1>Editing Status</h1>

<%= render 'form', status: @status %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<p id="notice"><%= notice %></p>
<div class="page-header">
  <h1>Socialville User Statuses</h1>
</div>
<%= link_to 'New Status', new_status_path, class: "btn btn-success btn-xs"  %>
<%= render "statuses/index" %>
<% @statuses.each do |status| %>
<div class="status">
  <li class="list-group-item">
    <div class="media">
      <div class="media-left">
        <span class="avatar avatar-online">
          <%= image_tag status.user.image.url(:thumb), class: "img-circle" %>
          <i></i>
        </span>
      </div>
      <div class="media-body">
        <h5 class="list-group-item-heading">
          <small class="pull-right"><%= link_to time_ago_in_words(status.created_at) + " ago", status %></small>
          <strong><%= status.name %></strong>
        </h5>
        <p class="list-group-item-text"><%= status.content %></p>
          <span class="admin">
            <%= link_to 'Edit', edit_status_path(status),class: "btn btn-info btn-xs" %>
            <%= link_to 'Destroy', status, method: :delete, 
          data: { confirm: 'Are you sure?' },class: "btn btn-danger btn-xs" %>
          </span>
      </div>
    </div>
  </li>
</div>
<% end %>

app/views/statuses/new.html.erb
<h1>New Status</h1>

<%= render 'form', status: @status %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<span class="admin"><%= link_to 'Edit', edit_status_path(@status) %></span>


<%= render 'statuses/show' %>
<div class="post-list">
    <div class="row">
        <div class="col-sm-2">
            <div class="picture">
                <%= image_tag @status.user.image.url(:thumb), class: "img-circle" %>
            </div>
        </div>
        <div class="col-sm-6">
            <h4>    
                <label class="label label-info"><%= @status.user.username %></label>
            </h4>
            <h5> 
            <i class="fa fa-calendar"></i>
            <%= time_ago_in_words(@status.created_at) + " ago" %>
            </h5>
            <p class="description"><%= @status.content %></p>    
        </div>
		<div class="col-sm-2" data-no-turbolink="">
      	<%= link_to 'Back', statuses_path, 
   		class: "btn btn-info btn-download btn-round pull-right makeLoading fa fa-share" %>  </div>
    </div>
</div>

app/views/users/_user.html.erb
<%= link_to user_path(user.username) do %>
<%= image_tag user.image.url(:micro), class: "img-circle" %>                                       
<% end %>

<h3><%= user.username %></h3>
<% if current_user %>
<p><%= action_buttons(user)%></p>
<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>
<h2>Profiles</h2>
<div class="btn-group" role="group" aria-label="Default Button Groups">
<%= link_to "Everyone", users_path, class: "btn btn-default #{'active' unless params[:people]}" %>
<%= link_to "Friends", users_path(people: "friends"), class: "btn btn-default #{'active' if params[:people] == 'friends'}" %>
<%= link_to "Requests", users_path(people: "requests"), class: "btn btn-default #{'active' if params[:people] == 'requests'}" %>
<%= link_to "Pending", users_path(people: "pending"), class: "btn btn-default #{'active' if params[:people] == 'pending'}" %>
</div>
</div>

<div class="container">
<div class="row">
<%= render @users %>
</div>
</div>